spring:
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm
  http:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 1000MB
  application:
    name: HC-MON-ms
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 200
      max-idle: 100
    timeout: 10000
  datasource:
        primary:
            url: jdbc:mysql://127.0.0.1:3306/laboratory?useUnicode=true&characterEncoding=UTF-8&useSSL=false
            driver-class-name: com.mysql.jdbc.Driver
            username: root
            password: root
            initialSize: 5
            minIdle: 5
            maxActive: 20
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20
            cachePrepStmts: true
        secondary:
            url: jdbc:mysql://127.0.0.1:3306/laboratory?useUnicode=true&characterEncoding=UTF-8&useSSL=false
            driver-class-name: com.mysql.jdbc.Driver
            username: root
            password: root
            initialSize: 5
            minIdle: 5
            maxActive: 20
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20
            cachePrepStmts: true
        thirdly:
            url: jdbc:mysql://127.0.0.1:3306/laboratory?useUnicode=true&characterEncoding=UTF-8&useSSL=false
            driver-class-name: com.mysql.jdbc.Driver
            username: root
            password: root
            initialSize: 5
            minIdle: 5
            maxActive: 20
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20
            cachePrepStmts: true
  jpa:
            show-sql: true
            hibernate:
              naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10086/eureka/
server:
  port: 8094
# mybatis
mybatis:   ## 可指定多个，用逗号或者分号隔开
  config-location: classpath:mybatis/MapperConfig.xml
  typeAliasesPackage: com.hc.entity
  mapperLocations: classpath:mybatis/sql/*.xml
#自定义数据   拦截器路径
system:
    publicPath: api/userInfoModela/userLogin
    tempFilePath: d:\file\temp
# pageHelp 分页插件

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

Android:
  baseUrl: C:\tool\tomcatServer\123\apache-tomcat-9.0.8\webapps\ROOT\apk\
  ipport:  http://www.sosum.net:8098/apk/


