server:
  port: 8000
spring:
  application:
    name: HC-TCP-ms
  #redis配置信息
#  redis:
#       host: 39.104.178.216
#       port: 6379
#       pool:
#         max-active: 200
#         max-idle: 100
#       timeout: 10000
  redis:
    cluster:
      nodes: 172.24.58.144:6380,172.24.58.145:6380,172.24.58.146:6380
      max-redirects: 3
    timeout: 60000
    pool:
      max-active: 300
      maxIdle: 100 #最大空闲连接数
      minIdle: 20 #最小空闲连接数
      maxWait: -1
  rabbitmq:
    host: 39.104.102.191
    port: 5672
    username: hc
    password: 123456
    virtual-host: HCMQ
    listener:
      simple:
        default-requeue-rejected: true
#socket配置信息
netty:
  ip: 127.0.0.1
  port: 8080
  bossGroupCount: 4
  wokerGroupCount: 8
  keepAlive: true
  backlog: 1024
##delphi 无线数据接收服务地址off:1 开 2关
#delphi:
#  offKey: 1