server:
  port: 10087
spring:
  application:
    name: HC-TCP-ms
  #redis配置信息
  redis:
       host: 192.168.1.90
       port: 6379
       pool:
         max-active: 200
         max-idle: 100
       timeout: 10000
  rabbitmq:
    host: 192.168.1.90
    port: 5672
    username: hc
    password: 123456
    listener:
      simple:
        default-requeue-rejected: true
    virtual-host: HCMQ
#socket配置信息
netty:
  ip: 127.0.0.1
  port: 8080
  bossGroupCount: 4
  wokerGroupCount: 8
  keepAlive: true
  backlog: 1024
##delphi 无线数据接收服务地址off:1 开 2关
#delphi:
#  offKey: 1