spring:
  application:
    name: HC-MSWK-ms
  rabbitmq:
    host: 192.168.1.90
    port: 5672
    username: hc
    password: 123456
    virtual-host: HCMQ
  datasource:
    url: jdbc:mysql://192.168.1.221:3306/laboratory?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: hc
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    logAbandoned: true      #打印超时错误
    removeAbandoned: true   # 设置自动连接超时回收
    removeAbandonedTimeout: 10
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    cachePrepStmts: true
  jpa:
    show-sql: true
    hibernate:
            naming:
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  output:
    ansi:
      enabled: detect
  redis:
    host: 192.168.1.90
    port: 6379
    pool:
       max-active: 200
       max-idle: 100
    timeout: 10000
server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.90:10086/eureka/
mybatis:   ## 可指定多个，用逗号或者分号隔开
  config-location: classpath:mybatis/MapperConfig.xml
  typeAliasesPackage: com.hc.entity
  mapperLocations: classpath:mybatis/laboratoryFrom/*.xml
hc:
  pyx:
   pc: 0.5
  ydg:
   pc: 3

