spring:
  application:
    name: HC-MSWK-ms
  rabbitmq:
    host: 39.104.102.191
    port: 5672
    username: hc
    password: 123456
    virtual-host: HCMQ
  datasource:
    url: jdbc:mysql://39.104.102.191:3306/laboratory?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: hclh
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    logAbandoned: true      #打印超时错误
    removeAbandoned: true   # 设置自动连接超时回收
    removeAbandonedTimeout: 10
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    cachePrepStmts: true
  jpa:
    show-sql: true
    hibernate:
            naming:
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  output:
    ansi:
      enabled: detect
#  redis:
#    host: 39.104.178.216
#    port: 6379
#    pool:
#       max-active: 200
#       max-idle: 100
#    timeout: 10000
  redis:
    cluster:
      nodes: 172.24.58.144:6380,172.24.58.145:6380,172.24.58.146:6380
      max-redirects: 3
    timeout: 60000
    pool:
      max-active: 300
      maxIdle: 100 #最大空闲连接数
      minIdle: 20 #最小空闲连接数
      maxWait: -1
#  #线程池配置信息
#  thread:
#    pool:
#      corePoolSize: 10
#      maxPoolSize: 100
#      keepAliveSeconds: 120
#      queueCapacity: 200
#      waitForTasksToCompleteOnShutdown: true
#      awaitTerminationSeconds: 30  
server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.104.178.216:8086/eureka/
mybatis:   ## 可指定多个，用逗号或者分号隔开
  config-location: classpath:mybatis/MapperConfig.xml
  typeAliasesPackage: com.hc.entity
  mapperLocations: classpath:mybatis/laboratoryFrom/*.xml
#delphi:
#  ip: 39.104.102.191
#  port: 9880
#  offKey: 2
hc:
  pyx:
   pc: 0.5
  ydg:
   pc: 3

