eureka:
  server:
#    enable-self-preservation: true
#  清理时间  eviction-interval-timer-in-ms: 4000
  client:
    fetch-registry: 'false'
    register-with-eureka: 'false'
    serviceUrl:
      defaultZone: http://localhost:10311/eureka/
server:
  port: '10311'
spring:
  application:
    name: HC-EUREKA-ms
