spring:
  application:
    name: HC-MSCT-ms
  cloud:
    config:
      discovery:
        serviceId: HC-MSCT-ms
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: hc
    password: 123456
    virtual-host: HCMQ
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/laboratory?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      cachePrepStmts: true
  jpa:
      show-sql: true
      hibernate:
              naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      output:
        ansi:
        enabled: detect
  redis:
      host: 127.0.0.1
      port: 6379
      pool:
        max-active: 1200
        max-idle: 100
      timeout: 10000
server:
  port: 8093
#  ssl:
#        key-store: classpath:tomcat.keystore
#        key-store-password: 123456
#        keyAlias: tomcat
#        keyStoreType: PKCS12
eureka:
#  instance:
#    hostname: 39.104.178.216
#    instance-id: ${spring.application.name}
#    prefer-ip-address: false
#    # 心跳检测检测与续约时间
#    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10086/eureka/
sms:
  ##产品名称:云通信短信API产品,开发者无需替换
  product: Dysmsapi
  ##产品域名,开发者无需替换
  domain: dysmsapi.aliyuncs.com
  accessKeyId: LTAI4Fh7qr78heUy5w69wfSm
  accessKeySecret: hWikSbW0g2cyNoTCvNd6OEXBEFBy0p
  ##短信签名
  signName: 互创实验室监控
   
CallBy:
  ##产品名称:云通信语音API产品,开发者无需替换
  product: Dyvmsapi
  ##产品域名,开发者无需替换
  domain: dyvmsapi.aliyuncs.com
  accessKeyId: LTAI4Fh7qr78heUy5w69wfSm
  accessKeySecret: hWikSbW0g2cyNoTCvNd6OEXBEFBy0p
  ##被叫显号,可在语音控制台中找到所购买的显号
  CalledShowNumber: "02759770206"
  ##Tts模板ID
  TtsID: TTS_196655486
           
mail:
  accessKey:
  accessSecret:
  ##控制台创建的发信地址
  AccountName:
  ##发信人昵称
  FromAlias:
  TagName:
timing:
  phone1: 13774664356
  phone2: 18108674918

logging:
  config: classpath:logback-spring.xml