eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8087
spring:
  application:
    name: HC-ZULL-ms
zuul:
  host:
#   max-per-route-connections: 60000
#   max-total-connections: 60000
   socket-timeout-millis: 60000
   connect-timeout-millis: 60000
  routes:
    api-mon:
      path: /api-mon/**
      serviceId: HC-MON-ms
    api-htgl:
      path: /api-htgl/**
      serviceId: HC-HTGL-ms
    api-msct:
      path: /api-msct/**
      serviceId: HC-MSCT-ms
    api-mswk:
      path: /api-mswk/**
      serviceId: HC-MSWK-ms
HC-MON-ms:
  ribbon:
    ReadTimeout: 600000
    ConnectTimeout: 600000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
